spring:
    application:
        name: pconnect-user
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/pconnect_auth?useUnicode=true&characterEncoding=UTF8
        username: root
        password: Neural!@#123
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
        host: localhost
        database: 7
        timeout: 1800
        pool:
          max-active: 8
          min-idle: 0
          max-idle: 0
          max-wait: -1
    mail:
        host: smtp.qq.com
        username: angularliu@qq.com
        password:  
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: false
                required: false

server:
    port: 8964

security:
    user:
        name: admin
        password: admin
        role: USER
    basic:
      enabled: false

mybatis:
    basepackage: cn.bgenius.pconnect.user.mapper
    xmlLocation: classpath:mapper/**/*.xml

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8961/eureka/

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #缺省为1000

logging:
    level:
        tk.mybatis: DEBUG
        cn.bgenius.pconnect.user: DEBUG
    config: classpath:logback.xml
    path: .

swagger:
    basepackage: cn.bgenius.pconnect.user.controller
    service:
        name: pconnect-user
        description: pconnect-user后端服务接口
        developer: F1